# Generated by Django 4.0.3 on 2022-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maximum_age_appropriate',
            field=models.IntegerField(default=-1),
        ),
    ]
